### PR TITLE
Reorganize generators

### PR DESCRIPTION
**Pull request by evanberkowitz**
If we can develop W≠1 Villain-formulation algorithms

    https://github.com/evanberkowitz/supervillain/issues/113
    https://github.com/evanberkowitz/supervillain/issues/112

it will behoove us to keep the generators a bit more organized.  Here I have separated the generators into Villain and Worldline, which parallels how the actions themselves are organized.

### CODE REVIEW

**Comment by evanberkowitz** [comment]
@SethBuesing since I don't want to cause trouble for your documentation, we can hold off on merging this.  Or, you can commit your latest changes here before we merge it.

**Comment by SethBuesing** [comment]
Oh I already put my latest changes in, that should be the most recent commit active

**Comment by SethBuesing** [comment]
> Oh I already put my latest changes in, that should be the most recent commit active

Other than that which you just added today

**Comment by evanberkowitz** [comment]
OK, then it should be safe to merge without disrupting your work.

**Pull request merged**
